### PR TITLE
New remote server on separate port

### PR DESCRIPTION
**Pull request by headwinds**
I went back and grabbed your old branch. You'll now find a "bensbranch" with that source so I don't lose it again ;-D. I lifted the server code from it and created a server folder.

So now I have all the demos working talking to a server on separate port; treat it as an API. For instance:

http://localhost:3001/gettreeData

Also, the routes now work if you go to http://localhost:3000/Bootstrap it will start the site with Bootstrap. I need to update the links later in the main library readme since we no longer have the # link.

I still need to style Bootstrap which I'll do later tonight if not tomorrow morning.

### CODE REVIEW

**Comment by bencripps** [comment]
would you mind rebasing your branch off the current master?

**Comment by headwinds** [comment]
rebase my master with your upstream master?

**Comment by bencripps** [comment]
there are a bunch of merge conflicts with this PR -- I would run `git rebase master` from your feature branch to rewind all your changes on top of the upstream.

**Comment by headwinds** [comment]
I'm not sure I want to rebase my work on top of the upstream master - I kinda want to force merge and blow out the past work - I'm confident my lastest master has everything we need to continue... 

I have a backup branch of your work here just in case I missed something:
https://github.com/headwinds/react-redux-grid-demo/tree/bensbranch

**Comment by headwinds** [comment]
Is possible for you to accept it as is and force merge my master so that it replaces your master? Or is rebasing the only option? Or any other thoughts?

**Comment by bencripps** [comment]
its possible, but it would force me to work through the merge conflicts, and since i wont know your work well, it's probably best if you do it -- thus requiring the rebase.

**Comment by headwinds** [comment]
Ok let's say I have a new branch called 'api' and I've checked it out 

So I think I need to a ```git rebase upstream master``` not  ``` git rebase master```  because I want to target your master branch not mine... right?

**Comment by bencripps** [comment]
correct, you wanna run git rebase bencripps/master, where bencripps is the name of the remote. if your remote is named upstream, youre good

**Comment by headwinds** [comment]
yep I added your repo as a remote upstream - so I should be good to go - I'll try that and get back to you

**Comment by headwinds** [comment]
Did that work?!?! I rebased with the remote upstream master - then I went through all the merge conflicts and resolved them -- committed and pushed again

**Comment by bencripps** [comment]
yup that worked!

**Comment by headwinds** [comment]
Third times the charm... After 3 aborts, and then finally I got a handle on the flow. Its a little hairy rebasing; keeping in mind the differences between your upstream and my remote but I learned a few things along the way. I didn't quite believe the green light that branch now has no conflicts which rocks.

So I still have to fix some style issues with Bootstrap and a couple other grids -- the paging looks off -- so I'll work on those and have an update tomorrow -- we're definitely over the mountain now

**Comment by bencripps** [comment]
make sure we add body-parser and serve-favicon to the package.json. i tried to run, and needed to install those modules before it would run. changes look awesome tho!

**Comment by headwinds** [comment]
will do - I also need to configure the server with a production env variable - it's currently hardcoded to localhost which is no good when you go to push to heroku

**Comment by headwinds** [comment]
I'm ready for another pull request - can you accept this one first before I make it? I've added the missing libraries to next pull and more...

**Pull request merged**
