### PR TITLE
White on white editable rows 

### PR DESCRIPTION
**Pull request by headwinds**
Alt update

So its looks like the build folder got committed in your master - I think I might have done that - and I'm trying to remove it as well as push a change to remove the white on white text from the editable cells. 

I'll open this pull request to discuss it not necessarily for you to accept it -- so discuss how to best do this update

### CODE REVIEW

**Comment by bencripps** [comment]
So the reason /build was added to the .git dir is because the build failed on the heroku server. I'm cool with deleting it, but we'll need to figure out how to get that working.

You've also got a bunch of merge conflicts, I think you need to rebase off the current version of master.

**Comment by bencripps** [comment]
After doing some research, all I can find is `create-react-apps` that commit their build to src.

**Comment by headwinds** [comment]
Yes I thought it was create-react-app... 

so for your heroku deployment, it looks at the github repo so the build folder is required? In which case, ok that make sense to keep it....

I'll work through the conflicts - If I restore the build folder, those 2 conflicts should go away

Before starting the fix, I did a pull on the upstream master but I didn't attempt to also rebase off it... I thought pulling was basically the same thing since it pulls and merges the latest but I'll see if rebase helps too

**Comment by bencripps** [comment]
Try cherry-picking your commit on top of bencripps/master -- it will make you work though the merge conflicts.

**Pull request closed without merging**
