### PR TITLE
First release of the create-react-app version

### PR DESCRIPTION
**Pull request by headwinds**
I've added some polish to the site
- new React Redux Grid logo
- 3 badges: stars, MIT, tweet 
- 4 examples (Bootstrap, Tree, ColRenderer do not work)
- the site is all react & redux now and should much more easier to maintain

I believe this is good shape to release now - I have more design plans once connect() is ready

hopefully you can also fix busted examples too before pushing to heroku - in theory they should be working now?!?

### CODE REVIEW

**Comment by bencripps** [comment]
Ok -- I'll merge and see if i can get the bugs fixed.

**Comment by bencripps** [comment]
Merged, changes look great!

**Comment by bencripps** [comment]
So the reason the other examples broke is because they are reteiving data aync from a remote resource, and you deleted the server portion of the app where it gets the data. 

I guess for now we can just get the data locally, so no big deal.

**Comment by headwinds** [comment]
ahhhh whoops - ok that make sense - locally is ok but now that I know what you were doing with the server probably good to bring it back and then explain what's happening; show that we can switch from local to remote data

**Pull request merged**
