### PR TITLE
bulk selection example

### PR DESCRIPTION
**Pull request by headwinds**
@bencripps 

I'm working on a new example featuring selection and bulk actions. 
[kapture](https://www.headwinds.net/lab/react-data-grid/kaptures/bulkSelectionDemo.mp4)

I have everything except setting a new pageIndex doesn't seem to update the grid. I believe the new pageSize is being passed into the grid. My pager is updating but the grid won't budge. Any ideas?

I've created a branch "bulk-selection" for you to review.

### CODE REVIEW

**Comment by bencripps** [comment]
This looks great! I think I know what the issue is; I won't have time to take a look at in depth tonight, but I totally will tomorrow. Once I fix the issue, I'll issue the PR to your branch!

**Comment by bencripps** [comment]
@headwinds how's it going with this, any new blockers?

**Comment by headwinds** [comment]
just work blockers ;-D - I haven't had a chance to finish the demo - I did actually use your fix in your production though! I should be able to complete it this weekend after our minor release crunch

**Comment by headwinds** [comment]
@bencripps I've done some work on this Bulk Selection branch and pushed it wanting to share some hurdles with you...

## Setting a new Row Limit & Page Number

It seems to only remember the new row limit on first numbered button click

I set the row limit to 50 rows, and click Page 1, I get page 1 with 50 rows however if I click Page 2, I get the original row limit of 10 and page 2 data. If I click Page 1 again, it renders correctly

## Select All Grid Indexes

If I check the select all check box, I don’t get the indexes array:
```
Object {row-0: true, row-1: true, row-2: true, row-3: true, row-4: true…}
```

If I check them individually, I get the desired indexes array

```
Object {lastUpdate: 9, row-2: true, indexes: Array[3], row-3: true, row-4: true}
```

## Types 

how do I import react-redux-grid types?


In my reducer, I simply copy and pasted the type that I wanted to listen to after seeing it logged in the console.

I want to be able to do:
```
import { GridTypes } from “react-redux-grid”;

case GridTypes.SET_DATA:
     return {
        ...state,
        recordsRemaining: [],
        recordsRemoved: []
      };
```
But instead I’m doing:

```
case "@@react-redux-grid/SET_DATA":
     return {
        ...state,
        recordsRemaining: [],
        recordsRemoved: []
      };
```

## 2 Grids 

Why can’t have 2 grids on the same page? In this Bulk Selection demo, I thought it would be cool to   also display the selected rows in a simple ```<Grid />``` below the list of selected emails... I've commented out that part. If I leave it in, nothing happens.

## Strange Undefined Action

the 3rd dispatch has an undefined action which I can’t seem to find ?!

action @ 16:55:42.584 @@router/LOCATION_CHANGE
action @ 16:55:42.669 @@react-redux-grid/SET_COLUMNS
action @ 16:55:42.680 undefined
action @ 16:55:42.681 @@react-redux-grid/DISMISS_EDITOR
action @ 16:55:42.698 @@react-redux-grid/SET_LOADING_STATE
action @ 16:55:42.880 @@react-redux-grid/SET_LOADING_STATE
action @ 16:55:42.905 @@react-redux-grid/SET_DATA

**Comment by bencripps** [comment]
Awesome, thanks for the feedback:

## Why cant I have two grids on the same page?

You most certainly can -- it's important to make sure both grids have a unique `stateKey`. Apart from that, there's nothing else to it. Let me know if you're still having trouble.

I think the undefined dispatch could be a `stateKey` related issue.

## Exporting Action Types

Yeah, this makes sense. We should open up an issue/enhancement for this.

## Select All/ Select Individual

As I mentioned before, this is a bug. We should open an issue for this, and get it remedied.

## Setting Row Limit

I'm betting this is an issue with how you're setting pageSize on your ajax request. When I get some time I will take a look at your branch and see if I can figure it out.

**Comment by bencripps** [comment]
Regarding the bug with keeping pageSize in memory --  this commit fixes that issue, https://github.com/bencripps/react-redux-grid-demo/commit/28e0678950f73fad90c5499b436aa5042f0588d3

**Comment by bencripps** [comment]
I think everything else you mentioned should be resolved.

**Comment by headwinds** [comment]
I pulled your branch update which fixed that row limit issue and then I added the page setting from your other example so now the only last thing to do is getting the second simple grid to show up for the party.

Also I went through some of your selection tests you and you do have one for all rows selected featuring the missing indexes so it's weird that I can't see them but as you mentioned we can test that again in another thread to make sure it's not a bug.

here's the test you wrote covering it

```
describe('The selectAll func in the selection reducer', () => {
    beforeEach(() => resetLastUpdate());

    const state = testState({
        'test-grid': new Selection({
            fakeRow: false,
            anotherRow: false
        })
    });

    const action = {
        type: SELECT_ALL,
        stateKey: 'test-grid',
        selection: {
            fakeRow: true,
            anotherRow: true
        },
        indexes: [0, 1]
    };

    it('Should return all rows as selected', () => {
        expect(
            selection(state, action).get('test-grid')
        ).toEqual(
            new Selection({
                fakeRow: true,
                anotherRow: true,
                indexes: [0, 1],
                lastUpdate: 1
            })
        );
    });

});
```

**Comment by bencripps** [comment]
I checked out the latest branch and it looks like everything is working well -- I don't see any code to create a second grid? Where is that?

**Comment by bencripps** [comment]
Ah I see it; I went ahead and removed a bunch of the code/logic and just got two grids to render side by side, so that's not the issue.

**Comment by headwinds** [comment]
fantastic! I'll check it out tonight

**Comment by headwinds** [comment]
@bencripps did you happen to check in your update to getBulkSelectionSelectedRows.js ? So the second simple grid will render now...

```
      return (<div>You have selected { ( undefined !== selectedIndexes ) ?  selectedIndexes.length : 0 } records with the following emails: 
                  <ul style={discStyle}>
                  {emails}
                  </ul>
                  {/*<Grid { ...simpleData } />*/}
                </div> )
```

**Comment by bencripps** [comment]
merged as part of #9

**Pull request closed without merging**
